
class MindFeedAIException(Exception):
    ...

class ConfigException(MindFeedAIException):
    ...

class RequestReaderException(MindFeedAIException):
    ...

class XMLReaderException(MindFeedAIException):
    ...

class HTMLReaderException(MindFeedAIException):
    ...

class AIClientException(MindFeedAIException):
    ...

class TransformerException(MindFeedAIException):
    ...
